export const orderFields = [
	'id',
	'orderNumber',
	'orderDateTime',
	'billingAddressId',
	'salesChannelId',
	'languageId',
	'stateId',
	'amountTotal',
	'amountNet',
	'shippingTotal',
	'taxStatus',
	'currencyId',
	'currencyFactor',
	'createdAt',
	'updatedAt',
	'customerComment',
	'affiliateCode',
	'campaignCode',
    'currency',
    'deliveries',
    'transactions',
    'lineItems',
];

export const salutationOptionFields = ['id', 'displayName'];
